### PR TITLE
Improve dinum synchro

### PR DESCRIPTION
**Pull request by simkim**

### CODE REVIEW

**Comment by bzg** [comment]
FWIW we plan a release on Nov 8th and this would help a lot to have this merged before Oct 31 so that we can deploy/test.

@andrew is there anything we can do to help review/improve this?

**Comment by andrew** [comment]
sorry I'd not being paying attention to this because it was a draft, hit the "ready to review" and I'll have a good look

**Comment by bzg** [comment]
Okay. Since I'm didn't write the code, I'll let @simkim hit the button.

**Comment by simkim** [comment]
One more fix commit, If CI pass it's good to me

**Comment by andrew** [comment]
🚢

**Comment by bzg** [comment]
Thank you both!

**Pull request merged**
