### PR TITLE
Allow to customize server url for the documentation with an env var

### PR DESCRIPTION
**Pull request by simkim**

### CODE REVIEW

**Comment by andrew** [comment]
You’ve got two different branches of code in this pr now FYI

also can you add some documentation for the env var?

**Comment by simkim** [comment]
Sorry, yes

**Comment by simkim** [comment]
Capture d’écran 2024-08-09 à 14 34 24

**Comment by simkim** [comment]
@andrew I added comment and a screenshot in PR

**Review by andrew — APPROVED** [review]

**Pull request merged**
